import Container from "@/components/container";
import Blogs from "@/components/blogs";
import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Blogs || HackFest challenge",
  description: "Generated by CSCC TEAM",
};
const Page: React.FC = () => {
  return (
    <Container>
      <Blogs />
    </Container>
  );
};

export default Page;
